# Generated by Django 3.0.8 on 2020-08-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Item'),
        ),
    ]
